-- User Table
CREATE TABLE IF NOT EXISTS user (
  id VARCHAR(50) PRIMARY KEY,
  pw VARCHAR(255) NOT NULL,
  username VARCHAR(50) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Arcade Table
CREATE TABLE IF NOT EXISTS arcade (
  arcade_id INT PRIMARY KEY AUTO_INCREMENT,
  EVENT_TITLE VARCHAR(255),
  EVENT_DETAIL TEXT,
  EVENT_START_DATE DATETIME,
  EVENT_END_DATE DATETIME,
  GAMECENTER_NAME VARCHAR(63),
  GAMECENTER_LOCATE VARCHAR(255),
  PATCH_TITLE VARCHAR(255),
  PATCH_DETAIL TEXT,
  PATCH_RELEASE_DATE DATETIME
);

-- PC Steam Table
CREATE TABLE IF NOT EXISTS pc_steam (
  pc_steam_id INT PRIMARY KEY AUTO_INCREMENT,
  EVENT_TITLE VARCHAR(255),
  EVENT_DETAIL TEXT,
  EVENT_START_DATE DATETIME,
  EVENT_END_DATE DATETIME,
  PATCH_TITLE VARCHAR(255),
  PATCH_DETAIL TEXT,
  PATCH_RELEASE_DATE DATETIME
);

-- PC Ranking Table
CREATE TABLE IF NOT EXISTS pc_ranking (
  ranking_id INT PRIMARY KEY AUTO_INCREMENT,
  SONG_NAME VARCHAR(255),
  ARTIST_NAME VARCHAR(127),
  PATTERN_DIFFICULTY VARCHAR(16),
  PATTERN_LV VARCHAR(4),
  PLAYER_NAME VARCHAR(63),
  BEST_SCORE BIGINT NOT NULL,
  CLEAR_TYPE VARCHAR(7)
);

-- Mobile Ranking Table
CREATE TABLE IF NOT EXISTS mobile_ranking (
  ranking_id INT PRIMARY KEY AUTO_INCREMENT,
  SONG_NAME VARCHAR(255),
  ARTIST_NAME VARCHAR(127),
  PATTERN_DIFFICULTY VARCHAR(16),
  PATTERN_LV VARCHAR(4),
  PLAYER_NAME VARCHAR(63),
  BEST_SCORE BIGINT NOT NULL,
  CLEAR_TYPE VARCHAR(7)
);

-- Mobile Table
CREATE TABLE IF NOT EXISTS mobile (
  mobile_id INT PRIMARY KEY AUTO_INCREMENT,
  EVENT_TITLE VARCHAR(255),
  EVENT_DETAIL TEXT,
  EVENT_START_DATE DATETIME,
  EVENT_END_DATE DATETIME,
  PATCH_TITLE VARCHAR(255),
  PATCH_DETAIL TEXT,
  PATCH_RELEASE_DATE DATETIME
);

-- Insert Sample Data
INSERT INTO arcade (
    EVENT_TITLE,
    EVENT_DETAIL,
    EVENT_START_DATE,
    EVENT_END_DATE,
    GAMECENTER_NAME,
    GAMECENTER_LOCATE,
    PATCH_TITLE,
    PATCH_DETAIL,
    PATCH_RELEASE_DATE
) VALUES (
    'Arcade Event Title 1',
    'Arcade Event Detail Information',
    '2025-12-20',
    '2025-12-31',
    'Amazing Arcade',
    'Seoul, Gangnam District',
    'Arcade Patch Title 1',
    'Arcade Patch Detail Information',
    '2025-12-10'
);

INSERT INTO pc_ranking (SONG_NAME, ARTIST_NAME, PATTERN_DIFFICULTY, PATTERN_LV, PLAYER_NAME, BEST_SCORE, CLEAR_TYPE) VALUES
  ('Neon Dreams', 'Synthwave Masters', 'Hard', '8', 'ProPlayer1', 999999, 'FC'),
  ('Electric Pulse', 'Beat Architects', 'Medium', '6', 'GameMaster2', 998888, 'Clear'),
  ('Digital Horizon', 'Cyber Sounds', 'Hard', '7', 'EliteGamer', 997777, 'FC'),
  ('Rainbow Road', 'Neon Velocity', 'Easy', '4', 'Casual Player', 996666, 'Clear'),
  ('Quantum Leap', 'Future Beats', 'Extreme', '10', 'Legend', 1000000, 'PFC');

INSERT INTO mobile_ranking (SONG_NAME, ARTIST_NAME, PATTERN_DIFFICULTY, PATTERN_LV, PLAYER_NAME, BEST_SCORE, CLEAR_TYPE) VALUES
  ('Mobile Song 1', 'Artist A', 'Normal', '5', 'MobilePlayer1', 950000, 'Clear'),
  ('Mobile Song 2', 'Artist B', 'Hard', '9', 'MobilePlayer2', 980000, 'FC');

INSERT INTO user (id, pw, username) VALUES
  ('admin', '$2a$10$rXJZPkC1Y2h8K0NzKFq3ve8vF4vF0YkGqZ3VxJPKxL.Wp5RmzZqWG', 'Admin User'),
  ('testuser', '$2a$10$rXJZPkC1Y2h8K0NzKFq3ve8vF4vF0YkGqZ3VxJPKxL.Wp5RmzZqWG', 'Test User');
